####Flight Price Prediction(EDA + Feature Engineering)

In [130]:
#importing basic libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [131]:
train_df=pd.read_excel('Data_Train.xlsx')
train_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [132]:
test_df=pd.read_excel('Test_set.xlsx')
test_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info
0,Jet Airways,6/06/2019,Delhi,Cochin,DEL → BOM → COK,17:30,04:25 07 Jun,10h 55m,1 stop,No info
1,IndiGo,12/05/2019,Kolkata,Banglore,CCU → MAA → BLR,06:20,10:20,4h,1 stop,No info
2,Jet Airways,21/05/2019,Delhi,Cochin,DEL → BOM → COK,19:15,19:00 22 May,23h 45m,1 stop,In-flight meal not included
3,Multiple carriers,21/05/2019,Delhi,Cochin,DEL → BOM → COK,08:00,21:00,13h,1 stop,No info
4,Air Asia,24/06/2019,Banglore,Delhi,BLR → DEL,23:55,02:45 25 Jun,2h 50m,non-stop,No info

In [133]:
final_df = pd.concat([train_df, test_df], ignore_index=True)
final_df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882.0
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0

In [134]:
final_df.tail()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
13349,Air India,6/06/2019,Kolkata,Banglore,CCU → DEL → BLR,20:30,20:25 07 Jun,23h 55m,1 stop,No info,NaN
13350,IndiGo,27/03/2019,Kolkata,Banglore,CCU → BLR,14:20,16:55,2h 35m,non-stop,No info,NaN
13351,Jet Airways,6/03/2019,Delhi,Cochin,DEL → BOM → COK,21:50,04:25 07 Mar,6h 35m,1 stop,No info,NaN
13352,Air India,6/03/2019,Delhi,Cochin,DEL → BOM → COK,04:00,19:15,15h 15m,1 stop,No info,NaN
13353,Multiple carriers,15/06/2019,Delhi,Cochin,DEL → BOM → COK,04:55,19:15,14h 20m,1 stop,No info,NaN

In [135]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Date_of_Journey  13354 non-null  object
 2   Source           13354 non-null  object
 3   Destination      13354 non-null  object
 4   Route            13353 non-null  object
 5   Dep_Time         13354 non-null  object
 6   Arrival_Time     13354 non-null  object
 7   Duration         13354 non-null  object
 8   Total_Stops      13353 non-null  object
 9   Additional_Info  13354 non-null  object
 10  Price            10683 non-null  float64
dtypes: float64(1), object(10)
memory usage: 1.1+ MB

In [136]:
# firstly, date of journey is in object form, and break it into date, month and year, basically a deriverd feature

In [137]:
### Feature Engineering process
final_df['Date_of_Journey'] = pd.to_datetime(final_df['Date_of_Journey'])
final_df['Date'] = final_df['Date_of_Journey'].dt.day
final_df['Month'] = final_df['Date_of_Journey'].dt.month
final_df['Year'] = final_df['Date_of_Journey'].dt.year

In [138]:
final_df.head(2)

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,2019-03-24,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,2019-05-01,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019

In [139]:
final_df.drop("Date_of_Journey",axis=1, inplace = True)

In [140]:
final_df['Arrival_Time']=final_df['Arrival_Time'].str.split(' ').str[0]

In [141]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019

In [142]:
final_df.isnull().sum()

Airline               0
Source                0
Destination           0
Route                 1
Dep_Time              0
Arrival_Time          0
Duration              0
Total_Stops           1
Additional_Info       0
Price              2671
Date                  0
Month                 0
Year                  0
dtype: int64

In [143]:
final_df['Arrival_hour']=final_df['Arrival_Time'].str.split(':').str[0]
final_df['Arrival_min']=final_df['Arrival_Time'].str.split(':').str[1]

In [144]:
final_df.head()

,Airline,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,22:20,01:10,2h 50m,non-stop,No info,3897.0,24,3,2019,01,10
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25,19h,2 stops,No info,13882.0,9,6,2019,04,25
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35

In [145]:
final_df['Arrival_hour']=final_df['Arrival_hour'].astype(int)
final_df['Arrival_min']=final_df['Arrival_min'].astype(int)

In [146]:
final_df.drop('Arrival_Time', axis=1,inplace=True)

In [147]:
final_df['Dept_hour']=final_df['Dep_Time'].str.split(':').str[0]
final_df['Dept_min']=final_df['Dep_Time'].str.split(':').str[1]
final_df['Dept_hour']=final_df['Dept_hour'].astype(int)
final_df['Dept_min']=final_df['Dept_min'].astype(int)
final_df.drop('Dep_Time', axis=1, inplace=True)

In [148]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13354 entries, 0 to 13353
Data columns (total 15 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13354 non-null  object
 1   Source           13354 non-null  object
 2   Destination      13354 non-null  object
 3   Route            13353 non-null  object
 4   Duration         13354 non-null  object
 5   Total_Stops      13353 non-null  object
 6   Additional_Info  13354 non-null  object
 7   Price            10683 non-null  float64
 8   Date             13354 non-null  int32
 9   Month            13354 non-null  int32
 10  Year             13354 non-null  int32
 11  Arrival_hour     13354 non-null  int64
 12  Arrival_min      13354 non-null  int64
 13  Dept_hour        13354 non-null  int64
 14  Dept_min         13354 non-null  int64
dtypes: float64(1), int32(3), int64(4), object(7)
memory usage: 1.4+ MB

In [149]:
final_df['duration_hour']=final_df['Duration'].str.split(' ').str[0].str.split('h').str[0]

In [150]:
final_df[final_df['duration_hour']=='5m']
# i think i should drop the 5m value as it looks incorrect logically
# how can mumbai to hyderabad take 5 min only
final_df = final_df[final_df['duration_hour'] != '5m']

In [151]:
final_df['duration_hour']=final_df['duration_hour'].astype('int')

In [152]:
final_df['duration_hour']*60

0         120
1         420
2        1140
3         300
4         240
         ...
13349    1380
13350     120
13351     360
13352     900
13353     840
Name: duration_hour, Length: 13352, dtype: int64

In [153]:
final_df['duration_min'] = final_df['Duration'].str.split(' ').str[1].str.split('m').str[0].fillna(0)
final_df['duration_min']= final_df['duration_min'].astype(int)

In [154]:
final_df['duration_min'] = final_df['duration_hour']*60 + final_df['duration_min']

In [155]:
final_df.head()

,Airline,Source,Destination,Route,Duration,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min,duration_hour,duration_min
0,IndiGo,Banglore,New Delhi,BLR → DEL,2h 50m,non-stop,No info,3897.0,24,3,2019,1,10,22,20,2,170
1,Air India,Kolkata,Banglore,CCU → IXR → BBI → BLR,7h 25m,2 stops,No info,7662.0,1,5,2019,13,15,5,50,7,445
2,Jet Airways,Delhi,Cochin,DEL → LKO → BOM → COK,19h,2 stops,No info,13882.0,9,6,2019,4,25,9,25,19,1140
3,IndiGo,Kolkata,Banglore,CCU → NAG → BLR,5h 25m,1 stop,No info,6218.0,12,5,2019,23,30,18,5,5,325
4,IndiGo,Banglore,New Delhi,BLR → NAG → DEL,4h 45m,1 stop,No info,13302.0,1,3,2019,21,35,16,50,4,285

In [156]:
final_df.drop('Duration', axis = 1, inplace=True)

In [157]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13352 entries, 0 to 13353
Data columns (total 16 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  object
 1   Source           13352 non-null  object
 2   Destination      13352 non-null  object
 3   Route            13351 non-null  object
 4   Total_Stops      13351 non-null  object
 5   Additional_Info  13352 non-null  object
 6   Price            10682 non-null  float64
 7   Date             13352 non-null  int32
 8   Month            13352 non-null  int32
 9   Year             13352 non-null  int32
 10  Arrival_hour     13352 non-null  int64
 11  Arrival_min      13352 non-null  int64
 12  Dept_hour        13352 non-null  int64
 13  Dept_min         13352 non-null  int64
 14  duration_hour    13352 non-null  int64
 15  duration_min     13352 non-null  int64
dtypes: float64(1), int32(3), int64(6), object(6)
memory usage: 1.6+ MB

In [158]:
final_df.drop('duration_hour', axis = 1, inplace=True)

In [159]:
final_df.drop('Route', axis = 1, inplace=True)

In [160]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13352 entries, 0 to 13353
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Airline          13352 non-null  object
 1   Source           13352 non-null  object
 2   Destination      13352 non-null  object
 3   Total_Stops      13351 non-null  object
 4   Additional_Info  13352 non-null  object
 5   Price            10682 non-null  float64
 6   Date             13352 non-null  int32
 7   Month            13352 non-null  int32
 8   Year             13352 non-null  int32
 9   Arrival_hour     13352 non-null  int64
 10  Arrival_min      13352 non-null  int64
 11  Dept_hour        13352 non-null  int64
 12  Dept_min         13352 non-null  int64
 13  duration_min     13352 non-null  int64
dtypes: float64(1), int32(3), int64(5), object(5)
memory usage: 1.4+ MB

In [161]:
final_df['Airline'].unique()

array(['IndiGo', 'Air India', 'Jet Airways', 'SpiceJet',
       'Multiple carriers', 'GoAir', 'Vistara', 'Air Asia',
       'Vistara Premium economy', 'Jet Airways Business',
       'Multiple carriers Premium economy', 'Trujet'], dtype=object)

In [162]:
# label encoding for the Airline and rest of categorical features
from sklearn.preprocessing import LabelEncoder
labelencoder= LabelEncoder()

In [163]:
final_df['Airline']=labelencoder.fit_transform(final_df['Airline'])
final_df['Source']=labelencoder.fit_transform(final_df['Source'])
final_df['Destination']=labelencoder.fit_transform(final_df['Destination'])
final_df['Additional_Info']=labelencoder.fit_transform(final_df['Additional_Info'])

In [168]:
final_df.head()

,Airline,Source,Destination,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min,duration_min
0,3,0,5,non-stop,8,3897.0,24,3,2019,1,10,22,20,170
1,1,3,0,2 stops,8,7662.0,1,5,2019,13,15,5,50,445
2,4,2,1,2 stops,8,13882.0,9,6,2019,4,25,9,25,1140
3,3,3,0,1 stop,8,6218.0,12,5,2019,23,30,18,5,325
4,3,0,5,1 stop,8,13302.0,1,3,2019,21,35,16,50,285

In [169]:
pd.get_dummies(final_df,columns=["Airline", "Source", "Destination"] ,drop_first = True)

,Total_Stops,Additional_Info,Price,Date,Month,Year,Arrival_hour,Arrival_min,Dept_hour,Dept_min,...,Airline_11,Source_1,Source_2,Source_3,Source_4,Destination_1,Destination_2,Destination_3,Destination_4,Destination_5
0,non-stop,8,3897.0,24,3,2019,1,10,22,20,...,False,False,False,False,False,False,False,False,False,True
1,2 stops,8,7662.0,1,5,2019,13,15,5,50,...,False,False,False,True,False,False,False,False,False,False
2,2 stops,8,13882.0,9,6,2019,4,25,9,25,...,False,False,True,False,False,True,False,False,False,False
3,1 stop,8,6218.0,12,5,2019,23,30,18,5,...,False,False,False,True,False,False,False,False,False,False
4,1 stop,8,13302.0,1,3,2019,21,35,16,50,...,False,False,False,False,False,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13349,1 stop,8,NaN,6,6,2019,20,25,20,30,...,False,False,False,True,False,False,False,False,False,False
13350,non-stop,8,NaN,27,3,2019,16,55,14,20,...,False,False,False,True,False,False,False,False,False,False
13351,1 stop,8,NaN,6,3,2019,4,25,21,50,...,False,False,True,False,False,True,False,False,False,False
13352,1 stop,8,NaN,6,3,2019,19,15,4,0,...,False,False,True,False,False,True,False,False,False,False
13353,1 stop,8,NaN,15,6,2019,19,15,4,55,...,False,False,True,False,False,True,False,False,False,False